---
name: changelog
permissions: write-all
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/changelog.yml@1.0.9
    secrets: inherit
    with:
      branch: 'master'
...
